databases:
  - name: bookertwo
    databaseName: bookertwo
    user: bookertwo

services:
  - type: web
    name: bookertwo
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bookertwo
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
